tosca_definitions_version: cloudify_dsl_1_3

imports:
  - http://cloudify.co/spec/cloudify/5.0.5/types.yaml
  - plugin:cloudify-kubernetes-plugin

inputs:
  gcp_credentials:
    type: string
  kubernetes_master:
    type: string
  verify_ssl:
    type: boolean
  debug:
    type: boolean
  validate_status:
    type: boolean
  allow_node_redefinition:
    type: boolean
  resource_path:
    type: string
  resource_template_variables:
    type: dict

node_templates:
  resource:
    type: cloudify.kubernetes.resources.FileDefinedResource
    properties:
      client_config:
        authentication:
          gcp_service_account: { get_secret: gcp_credentials }
        configuration:
          api_options:
            host: { get_input: kubernetes_master }
            verify_ssl: { get_input: verify_ssl }
            debug: { get_input: debug }
      validate_resource_status: { get_input: validate_status }
      allow_node_redefinition: { get_input: allow_node_redefinition }
      file:
        resource_path: { get_input: resource_path }
        template_variables: { get_input: resource_template_variables }
